# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: VMware-Lab

steps:
- script: |
    echo "=== Azure DevOps VMware Agent ==="
    hostname
    whoami

    echo "=== Terraform ==="
    terraform version

    echo "=== vCenter DNS ==="
    getent hosts VCSA.blue.local

    echo "=== vCenter HTTPS ==="
    curl -kI https://VCSA.blue.local
  displayName: 'Test Terraform and vCenter connectivity'
