trigger:
- main

pool:
  name: VMware-Lab

variables:
- group: VMware-Terraform-Secrets

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Terraform Init, Validate and Plan'
  inputs:
    azureSubscription: 'Azure-Terraform-State'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    addSpnToEnvironment: true
    inlineScript: |
      set -e

      echo "=== Agent ==="
      hostname
      whoami

      echo "=== Terraform ==="
      terraform version

      echo "=== Terraform Init ==="
      terraform init

      echo "=== Terraform Validate ==="
      terraform validate

      echo "=== Terraform Plan ==="
      terraform plan -input=false
  env:
    TF_VAR_vsphere_user: $(VSPHERE_USER)
    TF_VAR_vsphere_password: $(VSPHERE_PASSWORD)
    TF_VAR_vsphere_server: $(VSPHERE_SERVER)

    ARM_USE_AZUREAD: "true"
    ARM_USE_OIDC: "true"
    ARM_CLIENT_ID: $(servicePrincipalId)
    ARM_TENANT_ID: $(tenantId)
    ARM_OIDC_TOKEN: $(idToken)